Repository microsoft/AzUrlShortener, pull requests merged in 2020-12, with the labels that each got.

#231 Add Custom Domain Tutorial to V1 too
  medias/AddCustomDomain.png
  medias/AddCustomDomainDetails.png
  medias/Rule1.png
  medias/cf_addSite.png
  medias/cf_rules_details.png
  medias/cl_dns_details.png
  medias/domainProviderDNS.png
  medias/domainValidated.png
  post-deployment-configuration.md
Labels: documentation

#233 Fixing the mapping of the custom domain
  post-deployment-configuration.md
  src/adminTools/adminBlazorWebsite/src/adminBlazorWebsite.csproj
  src/shortenerTools/UrlList/UrlList.cs
  src/shortenerTools/UrlShortener/UrlShortener.cs
  src/shortenerTools/UrlUpdate/UrlUpdate.cs
  src/shortenerTools/settings.json
  src/shortenerTools/shortenerTools.csproj
Labels: Serverless-Backend, bug, dependencies, documentation

#217 Shortenvanitychanges
  src/shortenerTools/Domain/Utility.cs
  src/shortenerTools/Properties/PublishProfiles/patientcommsshortenertools2fxfh - Zip Deploy.pubxml
  src/shortenerTools/Properties/ServiceDependencies/patientcommsshortenertools2fxfh - Zip Deploy/profile.arm.json
Labels: Serverless-Backend, feature

#191 ID Collison between Generated and Vanity URLS
  src/shortenerTools/Domain/StorageTableHelper.cs
  src/shortenerTools/Domain/Utility.cs
Labels: Serverless-Backend, bug, claimed, hacktoberfest-accepted
